name: Publicar ERP

on:
  push:
    branches:
      - main
    paths:
      - "index.html"
      - ".github/workflows/deploy.yml"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages-erp
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Preparar site
        run: |
          mkdir site
          cp index.html site/index.html

      - name: Criar pacote do site
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Publicar
        id: deployment
        uses: actions/deploy-pages@v4
